galaxy_info:
  author: L-vandijken
  description: Installeert en configureert MariaDB
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy

dependencies: []
